# Generated by Django 6.0.2 on 2026-02-08 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactadmin',
            old_name='created_time',
            new_name='create_time',
        ),
        migrations.AlterField(
            model_name='contactadmin',
            name='email',
            field=models.EmailField(max_length=150),
        ),
        migrations.AlterField(
            model_name='contactadmin',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
